rm limitsResults_channel0.txt
rm limitsResults_channel1.txt
rm limitsResults_channel2.txt
rm limitsResults_channel3.txt
rm limitsResults_COMB.txt
rm limitsResults_COMB_EbEe.txt
rm limitsResults_ONLYEB_EbEe.txt

rm limitsResults_channel0_OBS.txt
rm limitsResults_channel1_OBS.txt
rm limitsResults_channel2_OBS.txt
rm limitsResults_channel3_OBS.txt
rm limitsResults_COMB_OBS.txt
rm limitsResults_ONLYEB_OBS.txt

cat limitsResults_channel0_BwSyst_w0.10_BwSyst.txt limitsResults_channel0_BwSyst_w2.00_BwSyst.txt limitsResults_channel0_BwSyst_w5.00_BwSyst.txt limitsResults_channel0_BwSyst_w7.00_BwSyst.txt limitsResults_channel0_BwSyst_w10.00_BwSyst.txt > limitsResults_channel0.txt
cat limitsResults_channel1_BwSyst_w0.10_BwSyst.txt limitsResults_channel1_BwSyst_w2.00_BwSyst.txt limitsResults_channel1_BwSyst_w5.00_BwSyst.txt limitsResults_channel1_BwSyst_w7.00_BwSyst.txt limitsResults_channel1_BwSyst_w10.00_BwSyst.txt > limitsResults_channel1.txt
cat limitsResults_channel2_BwSyst_w0.10_BwSyst.txt limitsResults_channel2_BwSyst_w2.00_BwSyst.txt limitsResults_channel2_BwSyst_w5.00_BwSyst.txt limitsResults_channel2_BwSyst_w7.00_BwSyst.txt limitsResults_channel2_BwSyst_w10.00_BwSyst.txt > limitsResults_channel2.txt
cat limitsResults_channel3_BwSyst_w0.10_BwSyst.txt limitsResults_channel3_BwSyst_w2.00_BwSyst.txt limitsResults_channel3_BwSyst_w5.00_BwSyst.txt limitsResults_channel3_BwSyst_w7.00_BwSyst.txt limitsResults_channel3_BwSyst_w10.00_BwSyst.txt > limitsResults_channel3.txt
cat limitsResults_COMB_BwSyst_w0.10_BwSyst.txt limitsResults_COMB_BwSyst_w2.00_BwSyst.txt limitsResults_COMB_BwSyst_w5.00_BwSyst.txt limitsResults_COMB_BwSyst_w7.00_BwSyst.txt  limitsResults_COMB_BwSyst_w10.00_BwSyst.txt > limitsResults_COMB.txt

cat limitsResults_channel0_BwSyst_w0.10_BwSyst_OBS.txt limitsResults_channel0_BwSyst_w2.00_BwSyst_OBS.txt limitsResults_channel0_BwSyst_w5.00_BwSyst_OBS.txt limitsResults_channel0_BwSyst_w7.00_BwSyst_OBS.txt limitsResults_channel0_BwSyst_w10.00_BwSyst_OBS.txt > limitsResults_channel0_OBS.txt
cat limitsResults_channel1_BwSyst_w0.10_BwSyst_OBS.txt limitsResults_channel1_BwSyst_w2.00_BwSyst_OBS.txt limitsResults_channel1_BwSyst_w5.00_BwSyst_OBS.txt limitsResults_channel1_BwSyst_w7.00_BwSyst_OBS.txt limitsResults_channel1_BwSyst_w10.00_BwSyst_OBS.txt > limitsResults_channel1_OBS.txt
cat limitsResults_channel2_BwSyst_w0.10_BwSyst_OBS.txt limitsResults_channel2_BwSyst_w2.00_BwSyst_OBS.txt limitsResults_channel2_BwSyst_w5.00_BwSyst_OBS.txt limitsResults_channel2_BwSyst_w7.00_BwSyst_OBS.txt limitsResults_channel2_BwSyst_w10.00_BwSyst_OBS.txt > limitsResults_channel2_OBS.txt
cat limitsResults_channel3_BwSyst_w0.10_BwSyst_OBS.txt limitsResults_channel3_BwSyst_w2.00_BwSyst_OBS.txt limitsResults_channel3_BwSyst_w5.00_BwSyst_OBS.txt limitsResults_channel3_BwSyst_w7.00_BwSyst_OBS.txt limitsResults_channel3_BwSyst_w10.00_BwSyst_OBS.txt > limitsResults_channel3_OBS.txt
cat limitsResults_COMB_BwSyst_w0.10_BwSyst_OBS.txt limitsResults_COMB_BwSyst_w2.00_BwSyst_OBS.txt limitsResults_COMB_BwSyst_w5.00_BwSyst_OBS.txt limitsResults_COMB_BwSyst_w7.00_BwSyst_OBS.txt  limitsResults_COMB_BwSyst_w10.00_BwSyst_OBS.txt > limitsResults_COMB_OBS.txt
